name: Backend Release (Railway)

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Rodzaj aktualizacji API (MAJOR/MINOR/PATCH)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Podbicie wersji z głównego pliku
        run: |
          OLD_VERSION=$(cat app-version.txt)
          NEW_VERSION=$(npx semver -i ${{ github.event.inputs.bump_type }} $OLD_VERSION)
          
          echo $NEW_VERSION > app-version.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit i Tag
        run: |
          git add app-version.txt
          git commit -m "backend-v${{ env.NEW_VERSION }}"
          git tag "backend-v${{ env.NEW_VERSION }}"

      - name: Push do repozytorium
        run: git push origin HEAD --follow-tags

      - name: Instalacja Railway CLI
        run: npm i -g @railway/cli

      - name: Publikacja na Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up ./backend --service fifowa-spoda-backend --detach